[versions]
shadow = "9.2.2"
invui = "1.47"
commandapi = "11.0.1-SNAPSHOT"
configlib = "4.6.4"
lombok = "1.18.42"
paper = "1.21.4-R0.1-SNAPSHOT"
commons-text = "1.14.0"
minitext = "v1.0.1"
zapper = "1.1.0"

[libraries]
invui = { group = "xyz.xenondevs.invui", name = "invui-core", version.ref = "invui" }
inventoryaccess = { group = "xyz.xenondevs.invui", name = "inventory-access-r23", version.ref = "invui" }
commandapi = { group = "dev.jorel", name = "commandapi-paper-shade", version.ref = "commandapi" }
configlib = { group = "de.exlll", name = "configlib-paper", version.ref = "configlib" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
minitext = { group = "com.github.Bruhdows", name = "MiniText", version.ref = "minitext" }

[bundles]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
zapper = { id = "net.oceanias.zapper", version.ref = "zapper" }